import 'package:flutter/material.dart';

class CatalogosVigilanciaSV {
  final _especie = [
    'No aplica',
    'ABACÁ (Musa textilis)',
    'ACACIA (Acacia sp.)',
    'ACELGA (Beta vulgaris var. Cicla)',
    'ACHILLEA (Achillea sp.)',
    'ACHIOTE (Bixa orellana)',
    'ACHIOTILLO (Nephelium lappaceum)',
    'ACHIRA (Canna indica)',
    'ACHOGCHA (Cyclanthera pedata)',
    'ACORDIÓN (Curculigo capitulata)',
    'AGAPANTHUS (Agapanthus sp.)',
    'AGAVE (Agave sp.)',
    'AGUACATE (Persea americana)',
    'AJÍ (Capsicum frutescens)',
    'AJO (Allium sativum)',
    'AJONJOLÍ (Sesamun indicum)',
    'ÁLAMO (Populus alba)',
    'ALBAHACA (Ocimum basilicum)',
    'ALCACHOFA (Cynara scolymus)',
    'ALFALFA (Medicago sativa)',
    'ALGODÓN (Gossypium herbaceum)',
    'ALHELÍ (Matthiola incana)',
    'ALISO (Alnus acuminata)',
    'ALMENDRA (Amygdalus communis)',
    'ALMIZCLILLO (Hibiscus abelmoschus)',
    'ALPINIA (Alpinia purpurata)',
    'ALSTROMELIA (Alstroemeria sp.)',
    'ALTERNATERA (Alternanthera bettzickiana)',
    'ALTERNATERA FUCCIA (Alternanthera purpurea)',
    'AMANCAY (Alstroemeria sp.)',
    'AMARANTO (Amaranthus  sp)',
    'AMARILLO (Aspidosperma australe)',
    'AMBRETTE (Abelmoschus moschatus)',
    'AMMI VISANAGA (Ammi visnaga)',
    'AMMIMAJUS (Ammi majus)',
    'ANEMONE (Anemone spp.)',
    'ANIGOZANTHOS (Anigozanthos sp.)',
    'ANÍS (Pimpinella anisum)',
    'ANTURIO (Anthurium sp)',
    'ANTURIO BLANCO (Anthurium andreanum)',
    'APIO (Apium graveolens)',
    'ARALIA (Polyscias fruticosa)',
    'ARÁNDANO (Vaccinium corymbosum)',
    'ARAUCARIA (Araucaria sp.)',
    'ARAZÁ (Eugenia stipitata)',
    'ARRAYÁN (Luma apiculata)',
    'ARROZ (Oryza sativa)',
    'ARVEJA (Pisum sativum)',
    'ASPIDISTRA (Aspidistra sp.)',
    'ASPLENIUM (Aspleniun spp.)',
    'ÁSTER (Aster sp.)',
    'AVENA (Avena sativa)',
    'AYAHUASCA (Banisteriopsis caapi)',
    'AZTEC GRASS (Liriope variegado)',
    'AZUCENA (Lilium candidum)',
    'BABACO (Carica pentagona)',
    'BABY BLUE (Oxypetalum)',
    'BADEA (Passiflora quadrangularis)',
    'BALSA (Ochroma pyramidale)',
    'BALSAMO (Myroxylon balsamun)',
    'BÁLSAMO (Myroxylon pereirae)',
    'BAMBÚ (Bambusa sp.)',
    'BANANO (Musa acuminata)',
    'BANANO MORADO (Musa spp.)',
    'BANANO ROJO (Musa rosacea)',
    'BARBA DE DRAGÓN (Ophiopogon japonicus)',
    'BEGONIA (Begonia semperflorens)',
    'BERENJENA (Solanum melongena)',
    'BIDENS (Bidens hybrid)',
    'BOLETO ANILLADO O BABOSILLO (Suillus luteus)',
    'BOROJÓ (Borojoa patinoi)',
    'BOUVARDIA (Bouvardia sp.)',
    'BRÓCOLI (Brassica oleracea var. Italica)',
    'BRODIAEA (Brodiaea sp)',
    'BROMELIA (Bromelia sp)',
    'BRUNIA (Brunia spp.)',
    'BUENA MADRE (Chlorophytum laxum)',
    'BUGANVILLA (Bougainvillea spp.)',
    'BUPLEURUM (Bupeurum sp.)',
    'CACAO (Theobroma cacao)',
    'CACTUS (Cactaceae)',
    'CAFÉ ARABIGO (Coffea arabica)',
    'CAFÉ ROBUSTA (Coffea canephora)',
    'CAIMITO (Chrysophillum cainito)',
    'CALAGUALA (Campyloneurum angustifolium',
    'CALATEA (Calathea sp.)',
    'CALATEA ZEBRA (Calathea zebrina)',
    'CALÉNDULA (Calendula officinalis)',
    'CALLISTEMON (Callistemon)',
    'CALLISTEPHUS (Callistephus chinensis)',
    'CAMARÓN DORADO (Pachystachys lutea)',
    'CAMOTE (Ipomoea batatas)',
    'CAMPANULA (Campanula sp.)',
    'CANCION DE LA INDIA (Dracaena reflexa)',
    'CANELA (Cinnamomum verum)',
    'CAÑA DE AZÚCAR (Saccharum officinarum)',
    'CAÑA GUADUA (Guadua angustifolia)',
    'CAOBA (Swietenia macrophylla)',
    'CAPULÍ (Prunus salicifolia)',
    'CARAMBOLA (Averrhoa carambola)',
    'CARDAMOMO (Elettaria cardamomum)',
    'CARDO (Silybum marianum)',
    'CARTHAMUS (Carthamus sp.)',
    'CARTUCHO (Zantedeschia sp.)',
    'CARYOPTERIS (Caryopteris spp.)',
    'CATIVO (Prioria capaifera)',
    'CAUCHO (Hevea brasiliensis)',
    'CEBADA (Hordeum vulgare)',
    'CEBOLLA BLANCA (Allium fistulosum)',
    'CEBOLLA COLORADA (Allium cepa)',
    'CEBOLLA PERLA (Allium cepa)',
    'CEBOLLIN (Allium schoenoprasum)',
    'CEDRO (Cedrela odorata)',
    'CEDRÓN (Lippia citriodora)',
    'CEIBO (Erythrina sp.)',
    'CELOCIA (Celocia sp.)',
    'CENIZO (Leucophyllum frutescens)',
    'CENTENO (Secale cereale)',
    'CEREZA (Prunus cerasus)',
    'CÉSPED (Poaceae)',
    'CHAMAEDOREA (Chamaedorea sp.)',
    'CHAMPIÑON (Agaricus bisporus)',
    'CHARÁN (Caesalpinia glabrata)',
    'CHAYA (Cnidoscolus aconitifolius)',
    'CHÍA (Salvia hispanica)',
    'CHIFLERAS (Schefflera arboricola)',
    'CHILCA (Baccharis dracunculifolia)',
    'CHINCHÍN (Azara microphylla)',
    'CHÍPARO (Cupresus sempervirens)',
    'CHIRIMOYA (Annona cherimola)',
    'CHIYANGUA (Erygium foetidum)',
    'CHOCHO (Lupinus sativus)',
    'CHONTA (Iriartea deltoidea)',
    'CHONTADURO (Bactris gasipaes)',
    'CHONTILLO (Andira spp.)',
    'CHUGCHUGUAZA (Maytenus aelivis)',
    'CHUNCHO (Cedrelinga cateneiformis)',
    'CIBOTIUM (Cibotium spp.)',
    'CICA (Cyca revoluta)',
    'CICLAMEN (Cyclamen persicum)',
    'CIDRA (Citrus limetta)',
    'CIDRO (Citrus medica)',
    'CILANTRO (Coriandrum sativum)',
    'CINERARIA (Jacobaea maritima)',
    'CIPRÉS (Cupressus sempervirens)',
    'CIPRES (Cupressus spp.)',
    'CIRUELA (Prunus domestica)',
    'CLAUDIA (Prunnus domestica)',
    'CLAVEL (Dianthus caryophyllus)',
    'CLAVELLíN (Brownea sp.)',
    'COCCULUS (Cocculus laurifolius)',
    'COCO (Cocos nucifera)',
    'COL (Brassica oleracea var. Viridis)',
    'COL DE BRUSELAS (Brassica oleracea var. gemmifera)',
    'COL MORADA (Brassica oleracea var. capitata f. rubra)',
    'COLA DE CABALLO (Equisetum sp.)',
    'COLA DE CABALLO GIGANTE (Equisetum giganteum)',
    'COLIFLOR (Brassica oleracea var. Botrytis)',
    'COLIO (Coleus blumei)',
    'COLORADO (Schinopsis balansae)',
    'CORDELÍN(Cordyline sp.)',
    'COSTILLA DE ADÁN (Monstera deliciosa)',
    'COSTUS (Costus sp.)',
    'CRASPEDIA (Craspedia sp.)',
    'CRISANTEMO (Chrysanthemum sp)',
    'CROTO (Codiaeum variegatum)',
    'CUCARDA (Hibiscus rosa-sinensis)',
    'CURCUMA (Curcuma longa)',
    'CYRTOMIUN (Cyrtomiun sp.)',
    'DELPHINIUM (Delphinium sp.)',
    'DIANELLA (Dianella tasmanica)',
    'DIANTHUS (Dianthus barbatus)',
    'DRACAENA (Dracaena sp.)',
    'DRAGONARIA (Antirrhinum majus)',
    'DURANTA (Duranta sp.)',
    'DURANTA GRANDE (Duranta erecta)',
    'DURANTA PEQUEÑA (Duranta repens)',
    'DURAZNO (Prunnus persica)',
    'DURIÓN (Durio zibethinus)',
    'ÉBANO (Diospyros ebenum)',
    'ENDIVIA (Cichorium endivia)',
    'ERYNGIUM (Eryngium sp.)',
    'ESPÁRRAGO (Asparagus officinalis)',
    'ESPINACA (Spinacia oleracea)',
    'ESTÁTICE (Limonium sp.)',
    'ESTEVIA (Stevia rebaudiana)',
    'ETLINGERA (Etlingera sp.)',
    'EUCALIPTO (Eucalyptus sp.)',
    'FALSA ÉRICA (Cuphea gracilis)',
    'FERNÁN SÁNCHEZ (Triplaris cumingiana)',
    'FICUS (Ficus sp.)',
    'FILODENDRO XANTAL (Philodendrum xantal)',
    'FLORIPONDIO (Brugmansia arborea)',
    'FREESIA (Freesia hybrida)',
    'FRÉJOL (Phaseolus vulgaris)',
    'FRÉJOL DE PALO ( Cajanus caján)',
    'FRESA (Fragaria vesca)',
    'GALATEA (Dieffenbachia bowmanii)',
    'GANDUL (Cajanus cajan)',
    'GARBANZO (Cicer arietinum)',
    'GERANIO (Pelargonium sp.)',
    'GERBERA (Gerbera sp.)',
    'GINGER (Alpinia purpurata)',
    'GIRASOL (Helianthus annus)',
    'GLADIOLO (Gladiolus sp.)',
    'GODETIA (Godethia sp.)',
    'GRAMALOTE (Panicum fasciculatum)',
    'GRANADILLA (Passiflora ligularis)',
    'GRANADO (Punica granatum)',
    'GROSELLA (Phyllanthus acidus)',
    'GUABA (Inga edulis)',
    'GUANÁBANA (Annona muricata)',
    'GUANTO (Brugmansia sp.)',
    'GUAYABA (Psidium guajava)',
    'GUAYACAN (Tabebuia guayacan)',
    'GUAYUSA (Ilex guayusa)',
    'GUINEO (Musa paradisiaca)',
    'GYPSOPHILA (Gypsophila paniculata)',
    'HABA (Vicia faba)',
    'HAYA (Fagus syvatica)',
    'HELECHO (Pteridium aquilinum)',
    'HELECHO CUERO (Rumohra adiantiformis)',
    'HELECHO MACHO (Nephrolepis exaltata)',
    'HELICONIA (Heliconia sp.)',
    'HIBISCUS (Hibiscus sp.)',
    'HIERBA LUISA (Aloysia triphylla)',
    'HIGO (Ficus carica)',
    'HORTENSIA (Hydrangea sp.)',
    'HUARANGO (Prosopis pallida)',
    'HUELE DE NOCHE (Cestrum nocturnum)',
    'HYPERICUM (Hypericum sp.)',
    'IXORA (Ixora spp)',
    'JACARANDA (Jacaranda mimosifolia)',
    'JACKFRUIT (Artocarpus heterophyllus)',
    'JAMAICA (Hibiscus sabdariffa)',
    'JENGIBRE (Zingiber officinale)',
    'JÍCAMA (Pachyrhizus erosus)',
    'KALANCHOE (Kalanchoe spp.)',
    'KALES (Brassica oleracea var. Sabellica)',
    'KIKUYO (Pennisetum clandestinum)',
    'KING GRASS (Pennisetum purpureum x Pennisetum typhoides)',
    'KIWANO (Cucumis metuliferus)',
    'LAUREL (Cordia alliodora)',
    'LAVANDA (Lavandula officinalis)',
    'LECHUGA (Lactuca sativa)',
    'LENGA (Notohofagus pumilio)',
    'LENTEJA (Lens culinaris)',
    'LEUCADENDRO (Leucadendron sp.)',
    'LEUCAENA (Leucaena leucocephala)',
    'LEUCOSPERMUM (Leucospermum spp.)',
    'LIATRIS (Liatris sp.)',
    'LIGUSTRUM (Ligustrum ovalifolium)',
    'LILIUM (Lilium sp.)',
    'LILY GRASS (Chlorophytum spp.)',
    'LIMA (Citrus latifolia)',
    'LIMÓN (Citrus limon)',
    'LIMÓN SÚTIL (Citrus aurantifolia)',
    'LIMONIUM (Limonium spp.)',
    'LINARIA (Linaria sp.)',
    'LINAZA (Linum usitatissimum)',
    'LIRIO (Iris sp.)',
    'LIRIO AFRICANO, AGAPANTO (Agapanthus africanus)',
    'LIRIO ARAÑA CARIBEÑO (Hymenocallis caribaea)',
    'LIRIOPE (Ophiopogon japonicas)',
    'LIRIOS (Iris sp.)',
    'LISIANTHUS (Eustoma grandiflorum)',
    'LLANTÉN (Plantago major)',
    'LUFFA (Luffa spp.)',
    'LYSIMACHIA (Lysimachia sp.)',
    'MACA (Lepidium meyenii)',
    'MAÍZ (Zea mays)',
    'MALANGA (Xanthosoma sagittifolium)',
    'MALVA (Malva sylvestris)',
    'MAMEY (Mammea americana)',
    'MANDARINA (Citrus nobilis)',
    'MANGLE (Rizophora mangle)',
    'MANGO (Mangifera indica)',
    'MANÍ (Arachis hypogaea)',
    'MANÍ FORRAJERO (Arachis pintoi)',
    'MANZANA (Malus domestica)',
    'MANZANILLA (Matricaria chamomilla)',
    'MAQUEÑO (Musa balbisiana)',
    'MARACUYÁ (Passiflora edulis)',
    'MARGARITAS (Chrysanthemun leaucanthemum)',
    'MARIGOLD (Tagetes sp.)',
    'MASCAREY (Hieronyma alchorneoides)',
    'MATICO (Piper aduncum)',
    'MELINA (Gmelina arborea)',
    'MELLOCO (Ullucus tuberosus)',
    'MELÓN (Cucumis melo)',
    'MENTA (Mentha piperita)',
    'MILLONARIA (Polyscias sp.)',
    'MIMOSA (Mimosa pudica)',
    'MINI ROSA (Rosa spp.)',
    'MIRAMELINDA (Impatiens walleriana)',
    'MIRTO (Murraya paniculata)',
    'MIRTO (Myrtus communis)',
    'MOLUCELLA (Mollucella sp.)',
    'MOMORDICA (Momordica charantia)',
    'MORA (Rubus glaucus)',
    'MORINGA (Moringa oleifera)',
    'MORTIÑO (Vaccinium floribundum)',
    'MUÉRDAGO (Viscum album)',
    'MUÑA (Mintostachys setosa)',
    'NABO (Brassica rapa)',
    'NARANJA (Citrus sinensis)',
    'NARANJILLA (Solanum quitoense)',
    'NECTARÍN (Prunus persica var. Nectarina)',
    'NEEM (Azadirachta indica)',
    'NERINE (Nerine spp.)',
    'NÍSPERO (Mespilus germanica)',
    'NOGAL (Juglans regia)',
    'NONI (Morinda citrifolia)',
    'NUEZ (Juglans regia)',
    'NUEZ MACADAMIA INTEGRIFOLIA (Macadamia integrifolia)',
    'OLIVO (Olea europaea)',
    'OREJA DE CONEJO (Stachys lanata)',
    'ORITO (Musa acuminata)',
    'ORMOSIA (Ormosia coutinhoi)',
    'ORNITHOGALUM (Ornithogalum sp.)',
    'ORQUÍDEA (Orchidaceae)',
    'ORTIGA (Urtica urens)',
    'PACHACO (Schizolobium parahybum)',
    'PAJA MACORA (Macora guinea)',
    'PAJA TOQUILLA (Carludovica palmata)',
    'PALMA (Coperte caatinga)',
    'PALMA ACEITERA (Elaeis guineensis)',
    'PALMA ARECA (Chrysalidocarpus lutescens)',
    'PALMA CICA (Cycas revoluta)',
    'PALMA DE BOTELLA (Hyophorbe lagenicaulis)',
    'PALMA DE COCO (Cocos nucifera)',
    'PALMA FENIX (Phoenix roebellini)',
    'PALMA WASHINGTON (Washingtonia filifera)',
    'PALMERA FÉNIX (Phoenix canariensis)',
    'PALMITO  (Bactris gasipaes)',
    'PALO DE AGUA (Dracaena fragrans)',
    'PALO SANTO (Bursera graveolens)',
    'PAMBIL (Iriartea deltoidea)',
    'PANDANO (Pandanus utilis)',
    'PANDANUS (Pandanus sp.)',
    'PAPA (Solanum tuberosum)',
    'PAPA ANDINA MIX (Solanum tuberosum ssp. Andigena)',
    'PAPA CHINA (Colocasia esculenta)',
    'PAPAYA (Carica papaya)',
    'PAPIRO ENANO (Cyperus haspan)',
    'PASA (Vitis vinifera)',
    'PASTO ALEMÁN (Echynochloa polystachya)',
    'PASTO BRAQUIARIA (Brachiaria decumbens)',
    'PASTO DALLIS (Paspalum dilatatum)',
    'PASTO GRAMA (Cynodon dactylon)',
    'PASTO MICAY (Axonopus micay)',
    'PASTO SABOYA (Panicum maximum)',
    'PATA DE VACA (Bauhinia forficata)',
    'PAULOWNIA (Paulownia sp.)',
    'PENSAMIENTO (Viola x wittrockiana)',
    'PEPINILLO  (Cucumis sativus)',
    'PEPINO (Cucumis sativus)',
    'PEPINO DULCE (Solanum muricatum)',
    'PERA (Pyrus communis)',
    'PEREGRINA (Hibiscus rosa-sinensis)',
    'PEREJIL (Petroselinum crispum)',
    'PHILODENDRO (Philodendrum sp.)',
    'PHLOX (Phlox sp.)',
    'PICO DE LORO (Heliconia psittacorum)',
    'PIG FACE, SOLANUM (Solanum mammosum)',
    'PIMENTÓN (Capsicum annuum)',
    'PIMIENTA (Piper nigrum)',
    'PIMIENTO (Capsicum annuum)',
    'PINO (Pinus spp.)',
    'PIÑA (Ananas comosus)',
    'PIÑÓN (Jatropha sp.)',
    'PITAHAYA (Hylocereus spp.)',
    'PITTOSPORUM (Pittosporum sp.)',
    'PLÁTANO (Musa paradisiaca)',
    'PLÁTANO (Musa x paradisiaca var. Maqueño)',
    'PLÁTANO VERDE  (Musa x paradisiaca var. Maqueño)',
    'PODOCARPUS (Podocarpus sp.)',
    'POINSETTIA ENANA (Euphorbia cyathophora)',
    'POMARROSA (Syzygium jambos)',
    'POMPON (Chrysanthemum morifolium)',
    'PONCHO DE INDIO (Calathea ornata)',
    'POTHOS (Epipremnum aureum)',
    'PROTEAS (Protea sp.)',
    'PUERRO (Allium ampeloprasum var. Porrum)',
    'QUINA (Cinchona spp.)',
    'QUINUA (Chenopodium quinoa)',
    'QUINUAL POLILEPYS(Polylepis spp.)',
    'QUISHUAR (Buddleja incana)',
    'RABANO (Raphanus sativus)',
    'RÁBANO (Raphanus sativus)',
    'RANUCULO (Ranunculus sp.)',
    'RANUNCULO (Ranunculus sp.)',
    'RAY GRASS (Lolium multiflorum)',
    'REMOLACHA (Beta vulgaris)',
    'RICINO (Ricinus communis)',
    'ROBLE (Quercus robur)',
    'ROHEO (Rhoeo spathacea tricolor)',
    'ROMANESCO (Brassica oleracea var. botrytis L.)',
    'ROMERO (Rosmarinus officinalis)',
    'ROSA (Rosa sp.)',
    'ROSA ACICULARIS (Rosa acicularis.)',
    'ROSA AFZELIANA (Rosa  afzeliana)',
    'ROSA AGRESTIS (Rosa agrestis)',
    'ROSA ALTAICA (Rosa  altaica)',
    'ROSA ANDEGAVENSIS (Rosa andegavensis)',
    'ROSA ANEMONIFLORA (Rosa  anemoniflora)',
    'ROSA ARABICA (Rosa arabica)',
    'ROSA ARKANSANA (Rosa  arkansana)',
    'ROSA ARVENSIS (Rosa arvensis)',
    'ROSA BAICALENSIS (Rosa baicalensis)',
    'ROSA BANKSIAE (Rosa banksiae)',
    'ROSA SLPINA (Rosa  slpina)',
    'RUSCUS (Ruscus sp.)',
    'SABILA/ALOE VERA (Aloe vera)',
    'SACHA INCHI (Plukenetia volubilis)',
    'SAMÁN (Samanea saman)',
    'SANDE (Brosimum sp.)',
    'SANDIA (Citrullus lanatus)',
    'SANDÍA (Citrullus lanatus)',
    'SANSEVIERA (Sanseviera sp.)',
    'SAUCE (Salix spp.)',
    'SCHEFLERA BICOLOR (Schefflera arboricola variegada)',
    'SCHEFLERA VERDE (Schefflera arboricola)',
    'SEIKE (Cedrelinga catenaeformis)',
    'SENECIO (Senecio sp.)',
    'SNAPDRAGON (Anthirrinum majus)',
    'SOLIDAGO (Solidago sp.)',
    'SOYA (Glycine max)',
    'SPATHIPHYLLUM (Spathiphyllum spp.)',
    'SPIRULINA (Spirulina platensis)',
    'SUCHE (Trichomycterus rivulatus)',
    'SUNBERRY (Solanum retroflexum)',
    'SUPIROSA (Lantana rugulosa)',
    'SWINGLE (Swinglea glutinosa)',
    'TABACO (Nicotina tabacum)',
    'TAGUA (Phytelephas aequatorialis)',
    'TAMARINDO (Tamarindus indica)',
    'TANGARE (Carapa guianensis)',
    'TARA (Caesalpinea spinosa)',
    'TÉ (Camellia sinensis)',
    'TE NEGRO (Camellia sinensis)',
    'TECA (Tectona grandis)',
    'TILO (Tilia sp.)',
    'TOMATE (Lycopersicon esculentum)',
    'TOMATE DE ÁRBOL (Solanum betaceum)',
    'TOMATE RIÑÓN (Lycopersicum esculentum)',
    'TOQUILLA (Carludovica palmata)',
    'TORONCHE (Vasconcellea sp.)',
    'TORONJA (Citrus paradisi macf)',
    'TORONJIL (Melissa officinalis)',
    'TRACHELIUM (Trachelium sp.)',
    'TRÉBOL (Trifolium repens)',
    'TRÉBOL BLANCO  (Trifolium repens)',
    'TREE FERN (Asparagus virgatus)',
    'TRIGO (Triticum aestivum)',
    'TULBAGIA (Tulbaghia violacea)',
    'TULIPAN (Tulipa sp.)',
    'TUNA (Opuntia ficus-indica)',
    'UÑA DE GATO (Uncaria tormentosa)',
    'UVA (Vitis vinifera)',
    'UVILLA (Physalis peruviana)',
    'VAINILLA (Vainilla sp.)',
    'VAINITA (Phaseolus vulgaris)',
    'VERANERA (Boungainvillea sp.)',
    'VERONICA (Veronica sp.)',
    'VIBURNUM (Viburnum sp.)',
    'VIROLA (Virola spp.)',
    'VIROLA BLANCA (Virola sebífera)',
    'VOACANGA (Voacanga africana)',
    'YUCA (Manihot esculenta)',
    'YUTE (Corchorus  spp.)',
    'ZAMBO (Cucurbita ficifolia)',
    'ZANAHORIA (Daucus carota)',
    'ZANAHORIA AMARILLA (Daucus carota)',
    'ZANAHORIA BLANCA (Arracacia xanthorrhiza)',
    'ZAPALLO (Cucurbita maxima)',
    'ZAPOTE (Matisia cordata)',
    'ZARZAPARILLA (Smilax aspera)',
    'ZEBRINA (Tradescantia zebrina)',
    'ZINGIBER (Zingiber sp.)',
    'ZUCCHINI (Cucurbita pepo)'
  ];

  final _unidad = ['--', 'Hectáreas', 'Kilogramos'];

  final _sitioOperacion = [
    '--',
    'AGENCIA DE CARGA',
    'CENTRO DE PROCESAMIENTO',
    'CAMPOS DE MULTIPLICACIÓN',
    'CENTRO DE CONSOLIDACIÓN',
    'CENTRO DE TRATAMIENTO',
    'CENTRO DE ACOPIO',
    'DEPÓSITO DE PLANTAS',
    'ESTACIÓN FITOSANITARIA',
    'ESTACIÓN EXPERIMENTAL',
    'JARDÍN CLONAL',
    'LABORATORIO DE MICROPROPAGACIÓN',
    'PLANTAS',
    'POSCOSECHA',
    'SITIO DE ALMACENAMIENTO Y/O ',
    'COMERCIALIZACIÓN DE SEMILLAS',
    'SITIO DE BENEFICIO DE SEMILLAS',
    'SITIO DE PRODUCCIÓN (CULTIVO)',
    'URBANA (PARQUE, AVENIDA, JARDÍN)',
    'VÍA',
    'VIVERO',
  ];

  final _condicionProduccion = ['--', 'CAMPO ABIERTO', 'INVERNADERO'];

  final _etapaCultivo = [
    'NO APLICA',
    'COSECHA',
    'POST-COSECHA',
    'DESARROLLO VEGETATIVO',
    'FRUCTIFICACIÓN',
    'PRE-COSECHA',
    'FLORACIÓN',
    'MACOLLAMIENTO/BROTACIÓN',
    'RASTROJO DE CAMPO'
  ];

  final _actividad = [
    'M. DE MALEZAS',
    'M. DE PLAGAS CUARENTENARIAS',
    'M. DE PLAGAS EN PRINCIPALES CULTIVOS',
    'M. DE PLAGAS TRANSITORIAS',
    'NOTIFICACIÓN FITOSANITARIA',
  ];

  final _manejoSitio = [
    'BUENO',
    'REGULAR',
    'MALO',
  ];

  final _diagnosticoVisual = [
    'NO APLICA',
    'Abutilon malacum',
    'Abutilon sp.',
    'Acalypha aristata',
    'Acalypha arvensis',
    'Acalypha mexicana',
    'Acalypha setosa',
    'Acalypha sp.',
    'Acanthoscelides obtectus',
    'Achatina fulica/Lissachatina fulica',
    'Achyranthes aspera',
    'Acidovorax avenae ss cattleyae',
    'Acidovorax konjaci',
    'Acidovorax sp.',
    'Acinetobacter guillouiae',
    'Aciotis rubricaulis (Mart. Ex DC.) Triana cf.',
    'Acmella brachyglossa',
    'Acmella repens',
    'Aconophora sp.',
    'Acromyrmex sp.',
    'Acyrthosiphon malvae',
    'Adenostemma viscosum',
    'Aeneolamia sp.',
    'Aethalion reticulatum',
    'Agallia sp.',
    'Ageratum conyzoides',
    'Agraulis sp.',
    'Agrobacterium sp.',
    'Agrostis sodiroana',
    'Agrotis ipsilon',
    'Ahasverus advena',
    'Aleurocanthus sp.',
    'Aleurocanthus woglumi',
    'Aleurodicus cocois',
    'Aleurodicus dispersus',
    'Aleurodicus floccissimus',
    'Aleurothrixus floccosus',
    'Aleurothrixus sp.',
    'Aleurotrachelus socialis',
    'Aleyrodidae sp.',
    'Allograpta oblicua',
    'Alobates pensylvanicus',
    'Alphitobius sp.',
    'Alternanthera ficoidea',
    'Alternaria alternata',
    'Alternaria solani',
    'Alternaria sp.',
    'Alternaria steviae',
    'Alurmus humeralis',
    'Amaranthus hybridus',
    'Amaranthus sp.',
    'Amblyseius sp.',
    'Amitus fuscipennis',
    'Amorbia sp.',
    'Anagallis arvensis',
    'Anastrepha distincta',
    'Anastrepha fraterculus',
    'Anastrepha macrura',
    'Anastrepha obliqua',
    'Anastrepha pickeli',
    'Anastrepha sp.',
    'Anastrepha striata',
    'Andrena sp.',
    'Aneilema umbrosum',
    'Anillo clorotico (Potyvirus)',
    'Anthicus sp.',
    'Anthonomus rubi',
    'Anthonomus sp.',
    'Antiteuchus sp.',
    'Aonidiella aurantii',
    'Aonidiella orientalis',
    'Aonidomytilus albus',
    'Aorolaimus sp.',
    'Aphaenogaster concolor',
    'Aphaenogaster rudis',
    'Aphelenchoides besseyi',
    'Aphelenchoides composticola',
    'Aphelenchoides fragariae',
    'Aphelenchoides sp.',
    'Aphelenchus sp.',
    'Aphidius ervi',
    'Aphis citricola',
    'Aphis craccivora',
    'Aphis fabae',
    'Aphis gossypii',
    'Aphis sp.',
    'Aphis spiraecola',
    'Aphrophora sp.',
    'Apinocis angustus',
    'Apion godmani',
    'Apion sp.',
    'Apium leptophyllum',
    'Araecerus fasciculatus',
    'Argia anceps',
    'Armitermes sp.',
    'Arorathrips mexicanus',
    'Asclepias curassavica',
    'Ascochyta phaseolorum',
    'Ascochyta pisi',
    'Ascochyta sp.',
    'Asistacia gangetica',
    'Aspergillus sp.',
    'Asperisporium caricae',
    'Asperisporium sp.',
    'Aspidiotus destructor',
    'Aspidiotus nerii',
    'Aspidiotus sp.',
    'Asterolecanium bambusae',
    'Astraea lobata',
    'Astrephia chaerophylloides',
    'Astylus bourgeois',
    'Asystasia gangetica',
    'Asystasia sp.',
    'Atherigona orientalis',
    'Atrachea vulgaris',
    'Atta cephalotes',
    'Atta colombica',
    'Atta laevigata',
    'Atta sp.',
    'Aulacaspis tubercularis',
    'Aulacorthum solani',
    'Automeris sp.',
    'Bacillus galactosidilyticus',
    'Bacillus licheniformis',
    'Bacillus marisflavi',
    'Bacillus safiensis',
    'Bactericera cockerelli',
    'Bactrocera sp.',
    'Bacus sp.',
    'Banana bunchy top virus (BBTV)',
    'Banana streak virus (BSV)',
    'Bastardia bivalvis',
    'Bathycoelia sp.',
    'Battus polydamas',
    'Begonia semiovata',
    'Bemisia sp.',
    'Bemisia tabaci',
    'Bidens alba',
    'Bidens anthemoides',
    'Bidens pilosa',
    'Bidens sp.',
    'Bidens triplinerva',
    'Bipolaris sp.',
    'Bistorta sp.',
    'Bitta affinis',
    'Blattellidae sp.',
    'Blechum pyramidatum',
    'Blissus sp.',
    'Borreria latifolia',
    'Borreria verticillata',
    'Bostrichus parallelus',
    'Botryodiplodia sp.',
    'Botryodiplodia theobromae',
    'Botryosphaeria sp.',
    'Botrytis cinerea',
    'Botrytis fabae',
    'Botrytis sp.',
    'Brachymyrmex sp.',
    'Brachypodium sp.',
    'Bradysia sp.',
    'Brassica napus',
    'Brassica nigra',
    'Brassica rapa',
    'Brevicoryne brassicae',
    'Brevipalpus phoenicis',
    'Bromus catharticus',
    'Browallia americana',
    'Bulbostylis sp.',
    'Burkholderia ambifaria',
    'Burkholderia gladioli',
    'Burkholderia glumae',
    'Burkholderia plantarii',
    'Burkholderia sp.',
    'Burkholderia vietnamiensis',
    'Bursaphelenchus cocophilus (Anillo rojo)',
    'Calandrinia micrantha',
    'Calceolaria tripartita',
    'Calyptocarpus wendlandii',
    'Camponotus sp.',
    'Caperonia palustris',
    'Caperonia sp.',
    'Capnodium citri',
    'Capnodium sp.',
    'Capsella bursa',
    'Capsella bursa-pastoris',
    'Caracoles y babosas',
    'Cardamine hirsuta',
    'Cardiospermum corindum',
    'Carpophilus dimidiatus',
    'Carpophilus hemipterus',
    'Carpophilus humeralis',
    'Carpophilus lugubris',
    'Carpophilus maculatus',
    'Carpophilus marginellus',
    'Carpophilus sp.',
    'Castilleja arvensis',
    'Castilleja scorzonerifolia',
    'Castnia sp.',
    'Castniomera humboldti',
    'Castniomera licus',
    'Cathartus quadricollis',
    'Cedecea lapagei',
    'Celosia virgata',
    'Cenchrus echinatus',
    'Cenchrus pilosus',
    'Centaurea sp.',
    'Centrosema sp.',
    'Cephaleuros sp.',
    'Cephaloleia sp.',
    'Ceramidia sp.',
    'Ceramidia viridis',
    'Ceratitis capitata',
    'Ceratocystis fimbriata',
    'Ceratocystis sp.',
    'Ceratoma fascialis',
    'Cerconota anonella',
    'Cerconota dimorpha',
    'Cercopidae',
    'Cercospora coffeicola',
    'Cercospora sp.',
    'Cercospora zeae-maydis',
    'Ceroplastes floridensis',
    'Ceroplastes sinensis',
    'Ceroplastes sp.',
    'Cerotoma sp.',
    'Cerpophilus marginellus',
    'Chaetanaphothrips orchidii',
    'Chaetanaphothrips signipennis',
    'Chaetocnema sp.',
    'Chaetomium spp.',
    'Charidotella sexpunctata',
    'Chenopodium album',
    'Chenopodium ambrosioides',
    'Chenopodium murale',
    'Chenopodium sp.',
    'Chionomus haywardi',
    'Chlorida festiva',
    'Chloris barbata',
    'Chloris inflata',
    'Chloris radiata',
    'Chlorophorus annularis',
    'Chrisoptus picticornis',
    'Chromobacterium violaceum',
    'Chrysanthemun stunt virus (CSVD00)',
    'Chrysocharis flacilla',
    'Chrysodeixis includens',
    'Chrysomphalus sp.',
    'Chrysopa sp.',
    'Chrysotus picticornis',
    'Cicadidae',
    'Ciccadelidae',
    'Cinara sp.',
    'Cissus verticillata',
    'Citrus tristeza virus (CTV)',
    'Cladosporium cucumerinum',
    'Cladosporium sp.',
    'Clidemia sessiliflora',
    'Clinopsocus sp.',
    'Coccus hesperidum',
    'Coccus sp.',
    'Coccus viridis',
    'Coelestermus sp.',
    'Colaspidema sp.',
    'Colaspis submetallica',
    'Coleopterus sp.',
    'Colletotrichum gloeosporioides',
    'Colletotrichum graminicola',
    'Colletotrichum sp.',
    'Conmelina sp.',
    'Conoderus exsul',
    'Conotelus obscurus',
    'Conyza bonariensis',
    'Conyza sp.',
    'Copitarsia decolora',
    'Coptoborus sp',
    'Coptoborus sp.',
    'Corcyra cephalonica',
    'Cordana sp.',
    'Cornu aspersum',
    'Coronopus didymus',
    'Coronopus sp.',
    'Corticium salmonicolor',
    'Corynespora sp.',
    'Corythaica sp.',
    'Corythucha gossypii',
    'Cosmopolites sordidus',
    'Cotesia sp.',
    'Cratosomus sp.',
    'Crematogaster sp.',
    'Criconemoides sp.',
    'Criconemoides spp.',
    'Crocidosema aporema',
    'Crotalaria incana',
    'Croton sp.',
    'Cryptocarenus seriatus',
    'Cryptolestes ferrugineus',
    'Cryptolestes sp.',
    'Cryptostigma guadua',
    'Ctenarytaina eucalypti',
    'Ctenarytaina spatulata',
    'Cucumber mosaic virus',
    'Cucumber Vein Yellowing Virus',
    'Cuphea calophylla',
    'Cuphea carthagenensis',
    'Cuphea racemosa',
    'Cuphea wrightii',
    'Curvularia lunata',
    'Curvularia sp.',
    'Cyanthillium cinereum',
    'Cyathula achyranthoides',
    'Cyathula prostrata',
    'Cyclanthera integrifolia',
    'Cyclanthera multiflorum',
    'Cycloneda sanguinea',
    'Cycloneda sp.',
    'Cydia sp.',
    'Cyitopeltis tennius',
    'Cylindrocarpon sp.',
    'Cyperus difformis',
    'Cyperus elegans',
    'Cyperus esculentus',
    'Cyperus hermaphroditus',
    'Cyperus iria',
    'Cyperus luzuale',
    'Cyperus ochraceus',
    'Cyperus odoratus',
    'Cyperus rotundus',
    'Cyperus sp.',
    'Cyperus tenuispica',
    'Cyperus virens',
    'Cyrtomenus bergi',
    'Cyrtotrachelus longipes',
    'Dactylapius coccus',
    'Dactylapius sp.',
    'Dalbulus maidis',
    'Dalea sp.',
    'Danaus plexippus',
    'Dargida grammivora',
    'Dasheen mosaic virus',
    'Dasiops sp.',
    'Datura sp.',
    'Datura stramonium',
    'Delphacodes kuscheli',
    'Demotispa neivai',
    'Demotispa sp.',
    'Dennstaedtiaeceae hipolepis',
    'Deroceras ivadens',
    'Deroceras reticulatum',
    'Desmanthus sp.',
    'Desmodium incanum',
    'Diabrotica sp.',
    'Diabrotica undecimpunctata',
    'Diactor bilineatus',
    'Diaphorina citri',
    'Diaspididae',
    'Diaspis boisduvalii',
    'Diaspis sp.',
    'Diatraea saccharalis',
    'Diatraea sp.',
    'Dickeya chrysanthemi',
    'Dictyla sp.',
    'Digitaria ciliaris',
    'Digitaria fuscescens',
    'Digitaria sanguinelis',
    'Digitaria violascens',
    'Dilophus sp.',
    'Dinoderus sp.',
    'Dione juno',
    'Diplodia pinea',
    'Diplodia sp.',
    'Ditylenchus destructor',
    'Ditylenchus sp.',
    'Dolichoderus bispinosus',
    'Dorilaymus spp.',
    'Dorymyrmex sp.',
    'Dothistroma pini',
    'Dothistroma sp.',
    'Drechslera sp.',
    'Drosophila lutzii',
    'Drosophila melanogaster',
    'Drosophila sp.',
    'Drymaria cordata',
    'Drymaria malachioodes',
    'Drymaria sp.',
    'Dryocoetes sp.',
    'Duplachionaspis divergens',
    'Dyciphus sp.',
    'Dysdercus sp.',
    'Dysmicoccus  brevipes',
    'Dysmicoccus  pinicolus',
    'Dysmicoccus bispinosus',
    'Dysmicoccus boninsi',
    'Dysmicoccus ciliaris',
    'Dysmicoccus neobrevipes',
    'Dysmicoccus sp.',
    'Dysmicoccus tillandsia',
    'Dysmicoccus vescum',
    'Dyssodia papposa',
    'Dytilenchus sp.',
    'Eacles sp.',
    'Echinichloa crusgalli',
    'Echinochloa colona',
    'Eclipta prostrata',
    'Ectatomma edentatum',
    'Elachiptera sp.',
    'Elaeidobius sp.',
    'Elasmopalpus lignosellus',
    'Eleusine indica',
    'Elsinoe sp.',
    'Emilia fosbergii',
    'Emilia sonchifolia',
    'Empoasca fabae',
    'Empoasca sp.',
    'Enterobacter aerogenes',
    'Enterobacter amnigenus',
    'Enterobacter asburiae',
    'Enterobacter cloacae',
    'Enterobacter cowanii',
    'Entomobrya sp.',
    'Eotetranychus lewisi',
    'Eotetranychus sexmaculatus',
    'Ephestia kuehniella',
    'Epitrix parvula',
    'Epitrix similaris',
    'Epitrix sp.',
    'Equisetum sp.',
    'Eragrostis glomerata',
    'Eragrostis mexicana',
    'Eragrostis nigricans',
    'Eragrostis pilosa',
    'Eragrostis sp.',
    'Erechtites hieracifolia',
    'Erigeron bonariensis',
    'Erinnyis ello',
    'Eriosoma lanigerum',
    'Erodium cicutarium',
    'Erosomyia sp.',
    'Erwinia carotovora',
    'Erwinia carotovora pv. chrysantemi',
    'Erwinia sp.',
    'Eryngium foetidum',
    'Espoasca sp.',
    'Estigmina chinensis',
    'Eulachnus rileyi',
    'Euphorbia graminea',
    'Euphorbia heterophylla',
    'Euphorbia hirta',
    'Euphorbia hyssopifolia',
    'Euphorbia nutans',
    'Euphorbia ophtalmica',
    'Euphorbia peplus',
    'Euphorbia sp.',
    'Euplatypus compositus',
    'Eupteryx artemisae',
    'Eusarcosis inconspicuus',
    'Eutectona machaeralis',
    'Euxesta eluta',
    'Euxesta mazorca',
    'Euxesta sp.',
    'Euxesta stigmatias',
    'Exiguobacterium acetylicum',
    'Faustinus apicalis',
    'Ferrisia consobrina',
    'Ferrisia sp.',
    'Ferrisia virgata',
    'Fimbristylis dichotoma',
    'Fimbristylis littoralis',
    'Folsomide parvulus',
    'Formica obscuripes',
    'Formica rufa',
    'Frankliniella australis',
    'Frankliniella brevicaulis',
    'Frankliniella occidentalis',
    'Frankliniella parvula',
    'Frankliniella schultzei',
    'Frankliniella sp.',
    'Frankliniella tuberosi',
    'Frankliniella gardeniae',
    'Fuertesimalva limensis',
    'Fuertesimalva sp.',
    'Fumaria parviflora',
    'Fusarium decemcellulare',
    'Fusarium mexicanum',
    'Fusarium oxysporum',
    'Fusarium oxysporum f.sp. chrysantemi',
    'Fusarium oxysporum f.sp. cubense R4T',
    'Fusarium oxysporum f.sp. elaeidis',
    'Fusarium solani',
    'Fusarium sp.',
    'Gaeumannomyces sp.',
    'Galinsoga parviflora',
    'Galinsoga quadriradiata',
    'Galofa cf. aegeon',
    'Gastrocopta sp.',
    'Gauemnnomyces sp.',
    'Genicularia sp.',
    'Geophila macropoda',
    'Geotrichum sp.',
    'Geotrigona fumipennis',
    'Geranium seemannii',
    'Geranium sp.',
    'Gerridius sp.',
    'Globodera pallida',
    'Globodera rostochiensis',
    'Globodera sp.',
    'Gloeosporium sp.',
    'Gnaphalium luteo-album',
    'Gnaphalium sp.',
    'Gnathocerus cf. maxillosus',
    'Gnathocerus cornutus',
    'Gonocerus sp.',
    'Gonodonta sp.',
    'Graphopsocus sp.',
    'Greenidea formosana',
    'Greenidea psidii',
    'Gynaikothrips ficorum',
    'Hapalis prolixus',
    'Happia sp.',
    'Heimia salicifolia',
    'Heilupus lauris',
    'Helicoltylenchus spp.',
    'Helicotylenchus dihystera',
    'Helicotylenchus erythrinae',
    'Helicotylenchus multicinctus',
    'Helicotylenchus sp.',
    'Helicoverpa zea',
    'Heliothis sp.',
    'Heliotropium angiospermum',
    'Heliotropium indicum',
    'Heliotropium macrostachyum',
    'Helix aspersa',
    'Helminthosporium maydis',
    'Helminthosporium sp.',
    'Helycotilenchus multicinctus',
    'Hemiberlesia sp.',
    'Hemileia sp.',
    'Hemileia vastatrix',
    'Herbaspirillum huttiense',
    'Heteranthera sp.',
    'Heterodera sp.',
    'Hippobroma longiflora',
    'Hippodamia convergens',
    'Hirschmanniella sp.',
    'Hirtodrosophila cf. confusa',
    'Hispoleptis sp.',
    'Histotylenchus sp.',
    'Holcus lanatus',
    'Homolepis aturensis',
    'Horiola arcuata',
    'Horiola sp.',
    'Hospitalitermes sp.',
    'Huanglongbing (HLB)',
    'Hyadaphis sp.',
    'Hybanthus attenuatus',
    'Hyblaea puera',
    'Hydatothrips argenticinctus',
    'Hydrellia sp.',
    'Hyperdiplosis sp.',
    'Hypochaeris radicata',
    'Hypolepis eurychlaena',
    'Hypolepis thysanochlaena',
    'Hypoponera sp.',
    'Hypothenemus brunneus',
    'Hypothenemus eruditus',
    'Hypothenemus hampei',
    'Hypothenemus obscurus',
    'Hypothenemus seriatus',
    'Hypsipyla grandella',
    'Hyptis capitata',
    'Hyptis sp.',
    'Icerya purchasi',
    'Icerya sp.',
    'Indeterminado',
    'Insecto Inmaduro',
    'Insignorthezia l. insignis',
    'Ipomea leucantha',
    'Ipomea sp.',
    'Ipomoea purpurea',
    'Iresine diffusa',
    'Ischaemun rugosum',
    'Isotoma sp',
    'Jaegeria hirta',
    'Jaltomata sp.',
    'Julus sp.',
    'Justicia ramulosa',
    'Kakothrips sp.',
    'Kearnemalvastrum lacteum',
    'Klaprotia fasciculata',
    'Klebsiella oxytoca',
    'Lactococcus garvieae',
    'Lagascea mollis',
    'Lagascea sp.',
    'Laportea aestuans',
    'Lasioderma serricorne',
    'Lasiodiplodia spp',
    'Lasiodiplodia theobromae',
    'Latrophobia sp',
    'Lecanicillium sp.',
    'Lecanoideus sp.',
    'Lehmannia valentiana',
    'Lepechinia sp.',
    'Lepidium bipinnatifidum',
    'Lepidium sp.',
    'Lepidium virginicum',
    'Lepidosaphes beckii',
    'Lepidosaphes cf. gloverii',
    'Lepthosphaerella sp.',
    'Leptochloa scabra',
    'Leptoglossus sp.',
    'Leptoglossus zonatus',
    'Leptosphaeria sp.',
    'Leucoptera coffeella',
    'Leveillula sp.',
    'Limacus flavus',
    'Limacus sp.',
    'Limnocharis flava',
    'Lincus curvatus',
    'Liposcelis sp.',
    'Líquenes',
    'Liriomyza huidobrensis',
    'Liriomyza sativae',
    'Liriomyza sp.',
    'Liriomyza trifolii',
    'Lobesia botrana',
    'Lolium multiflorum',
    'Longidorus sp.',
    'Lophodermium sp.',
    'Lopholeucaspis cockerelli',
    'Ludwigia erecta',
    'Ludwigia octovalvis',
    'Ludwigia sp.',
    'Lyonetia sp.',
    'Maconellicoccus hirsutus',
    'Macroptilium atropurpureum',
    'Macroptilium sp.',
    'Macropygium sp.',
    'Macrosiphum euphorbiae',
    'Macrosiphum sp.',
    'Macrostola straminea',
    'Macrostylus sp.',
    'Mahanarva andigena',
    'Mahanarva bipars',
    'Malachra radiata',
    'Malachra ruderalis',
    'Malachra sp.',
    'Malva parviflora',
    'Malvaceae sidastrum',
    'Malvastrum coromandellanun',
    'Mancha de asfalto (Complejo)',
    'Manchado de grano arroz (Complejo)',
    'Manduca sexta',
    'Maracayia chlorisalis',
    'Maracayia spp.',
    'Marchitez letal',
    'Marchitez sorpresiva',
    'Marssonina sp.',
    'Mecinus sp.',
    'Medicago polymorpha',
    'Medicago sp.',
    'Megaselia sp.',
    'Melampodium perfoliatum',
    'Melanaphis sacchari',
    'Melanoides sp.',
    'Melanoides tuberculata',
    'Melanorhopala sp.',
    'Melanthera sp.',
    'Meloidogyne arenaria',
    'Meloidogyne incognita',
    'Meloidogyne sp.',
    'Melyridae',
    'Membracidae',
    'Membracis dorsata',
    'Membracis foliatafasciata',
    'Membracis sp.',
    'Mentzelia aspera',
    'Metamasius hemipterus',
    'Metamasius sp',
    'Metcalfiella sp.',
    'Metcalfiella vicina',
    'Miconia benthamiana triana',
    'Micosphaerella fijiensis',
    'Microcerotermes sp.',
    'Microcyclus ulei',
    'Milax gagates',
    'Mildiu sp.',
    'Mimosa debilis',
    'Mitracarpus hirtus',
    'Mitracarpus sp.',
    'Mocis latipes',
    'Momordica charantia',
    'Monalonium dissimulatum',
    'Monalonium sp.',
    'Monilia sp.',
    'Moniliophthora perniciosa',
    'Moniliophthora roreri',
    'Moniliophthora sp.',
    'Mucor sp.',
    'Muestra no procesada',
    'Muestra parasitada',
    'Muestra recibida en mal estado',
    'Mycena citricolor',
    'Mycena sp.',
    'Mycosphaerella fijiensis',
    'Mycosphaerella fragariae',
    'Mycosphaerella musicola',
    'Mycosphaerella sp.',
    'Mycrociclus ulei',
    'Myroides odoratimimus',
    'Myrothecium sp.',
    'Mystrops sp.',
    'Myzus persicae',
    'Nacobbus aberrans',
    'Nacobbus sp.',
    'Nasutitermes sp.',
    'Necrobia rufipes',
    'Nectria sp.',
    'Nelumbo lutea',
    'Neolcytus pusillus',
    'Neoleucinodes elegantalis',
    'Neosilba sp.',
    'Neotoxoptera formosana',
    'Nesidiocoris tenuis',
    'Nicandra physalodes',
    'Nicandra sp.',
    'Nigrospora sp.',
    'Nipaecoccus nipae',
    'Nipaecoccus sp.',
    'Nipaecoccus viridis',
    'Niptus hololeucus',
    'Nylanderia sp.',
    'Nysius sp.',
    'Ochrogaster sp.',
    'Odoiporus longicollis',
    'Oebalus insularis',
    'Oebalus ornatus',
    'Oebalus pugnax',
    'Oenomaus ortygnus',
    'Oenothera elata',
    'Oenothera rosea',
    'Oenothera sp.',
    'Oidium neolycopersici',
    'Oidium sp.',
    'Oiketicus kirbyi',
    'Oiketicus sp.',
    'Oligonychus sp.',
    'Oligonychus yothersi',
    'Olivea tectonae',
    'Olyra latifolia',
    'Oncideres digna',
    'Oncometopia c.f. Clarior',
    'Onychiurus sp.',
    'Opsiphanes cassina',
    'Orpinus fulvipes',
    'Orthezia praelonga',
    'Orthezia sp.',
    'Orthotylus sicilianus',
    'Oryza grandiglumis',
    'Oryza latifolia',
    'Oryzaephilus mercator',
    'Oryzaephilus sp.',
    'Oryzaephilus surinamensis',
    'Othezia sp.',
    'Oxalis barrelieri',
    'Oxalis corniculata',
    'Oxalis sp.',
    'Oxythyrea funesta',
    'Paenibacillus taichungensis',
    'Pagiocerus frontalis ',
    'Palmicola sp.',
    'Panicum maximum',
    'Panicum polygonatum',
    'Panicum sp.',
    'Panicum trichoides',
    'Pantoea agglomerans',
    'Papaver somniferum',
    'Papaya ringspot virus (PRSV)',
    'Paracoccus marginatus',
    'Paracoccus sp.',
    'Parajalysus tenuicornis',
    'Paraleyrodes sp.',
    'Paratylenchus sp.',
    'Parisoschoenus sp.',
    'Parthenium bipinnatifidum',
    'Parthenium hysterophorus',
    'Parthenium sp.',
    'Paspalum fasciculatum',
    'Paspalum paniculatum',
    'Paspalum prostratum',
    'Pectobacterium atrosepticum',
    'Pectobacterium carotovorum ss. carotovorum',
    'Pectobacterium cartovorum',
    'Pectobacterium cypripedii',
    'Pellicularia koleroga',
    'Pellicularia sp.',
    'Penicillium sp.',
    'Pennisetum clandestinum',
    'Pennisetum polystachium',
    'Pennisetum sp.',
    'Pentalonia nigronervosa',
    'Pentatomidae',
    'Peperomia pellucida',
    'Periconia sp.',
    'Perileucoptera sp.',
    'Perkinsiella saccharicida',
    'Perkinsiella sp.',
    'Peronospora anemones',
    'Peronospora destructor',
    'Peronospora farinosa',
    'Peronospora sp.',
    'Peronospora sparsa',
    'Persicaria nepalensis',
    'Pestalotia sp.',
    'Phaedon sp.',
    'Phaeoisariopsis griseola',
    'Phakopsora sp.',
    'Phasmatidae sp.',
    'Pheidole sp.',
    'Phenacoccus madeirensis',
    'Phenacoccus psidiarum',
    'Phenacoccus solenopsis',
    'Phenacoccus sp.',
    'Phenax sp.',
    'Phenococcus parvus',
    'Philonis passiflorae',
    'Phobetron sp.',
    'Phoma sp.',
    'Phomopsis sp.',
    'Phonoctonus sp.',
    'Phoradendron sp.',
    'Photinus sp.',
    'Phragmidium sp.',
    'Phthiracarus sp.',
    'Phthorimaea operculella',
    'Phyllachora maydis',
    'Phyllachora sp.',
    'Phyllanthus compressus',
    'Phyllanthus niruri',
    'Phyllocnistis citrella',
    'Phyllocnistis sp.',
    'Phyllocoptruta oleivora',
    'Phyllonorycter sp.',
    'Phyllophaga sp.',
    'Physa sp.',
    'Physalis philadelphica',
    'Physalis sp.',
    'Physopella sp.',
    'Phytolacca rivinoides',
    'Phytolacca rivinoides kunth & C.D. Bounché cf.',
    'Phytolacca sp.',
    'Phytophthora capsici',
    'Phytophthora cinnamomi',
    'Phytophthora citrophthora',
    'Phytophthora cryptogea',
    'Phytophthora infestans',
    'Phytophthora palmivora',
    'Phytophthora sp.',
    'Phytoptus matisiae',
    'Pinnaspis aspidistrae',
    'Pinnaspis sp.',
    'Piperaceae peperomia',
    'Pirycularia oryzae',
    'Pithomyces sp.',
    'Pityrogramma calomelanos',
    'Plaesius javanicus',
    'Planococcus citri',
    'Planococcus lilacinus',
    'Planococcus sp.',
    'Planorbis sp.',
    'Plantago alismatifolia',
    'Plantago lanceolata',
    'Plantago major',
    'Plantago sp.',
    'Plasmodiophora sp.',
    'Plasmopara halstedii',
    'Plasmopara sp.',
    'Platystethus sp.',
    'Plutella xylostella',
    'Poa annua',
    'Poaceae echinochloa',
    'Podagrica sp.',
    'Podischnus agenor',
    'Podisus sp.',
    'Poekilloptera phalaenoides',
    'Polygonaceae',
    'Polygonum acuminatum',
    'Polygonum aviculare',
    'Polygonum nepalense',
    'Polygonum punctatum',
    'Polygonum sp.',
    'Polypodium vulgares',
    'Polypogon elongatus',
    'Polytus sp.',
    'Pomacea canaliculata',
    'Porcellio scaber',
    'Porphyrobaphe iostoma',
    'Portulaca oleracea',
    'Potato virus S (PVS)',
    'Potato Virus X (PVX)',
    'Potyvirus',
    'Pratylenchus sp.',
    'Premnotrypes vorax',
    'Presencia de musgos y líquenes',
    'Priva lappulacea',
    'Prodiplosis longifila',
    'Protearomyia sp.',
    'Protopulvinaria sp.',
    'Pseudechinolaena polystachya',
    'Pseudelephantopus spicatus',
    'Pseudocercospora fijiensis',
    'Pseudocercospora sp.',
    'Pseudococcidae',
    'Pseudococcus calceolariae',
    'Pseudococcus citri',
    'Pseudococcus elisae',
    'Pseudococcus longispinus',
    'Pseudococcus jackbeardsleyi',
    'Pseudococcus sp.',
    'Pseudococcus viburni',
    'Pseudoelefantopus spicatus',
    'Pseudomonas fluorescens',
    'Pseudomonas luteola',
    'Pseudomonas maculicola',
    'Pseudomonas putida',
    'Pseudomonas sp.',
    'Pseudomonas tolaasii',
    'Pseudomonas viridilivida',
    'Pseudoperonospora cubensis',
    'Pseudoperonospora sp.',
    'Pseudopeziza sp.',
    'Pseudoplusia includens',
    'Psilenchus sp.',
    'Psococerustris sp.',
    'Psyllaephagus bliteus',
    'Psyllaephagus pilosus',
    'Ptinus tectus',
    'Puccinia horiana',
    'Puccinia kuehnii',
    'Puccinia melanocephala',
    'Puccinia pitteriana',
    'Puccinia sorghi',
    'Puccinia sp.',
    'Puccinia striiformis',
    'Pucciniopsis sp.',
    'Pudrición del cogollo (Complejo)',
    'Pueraria phaseoloides',
    'Pullus sp.',
    'Pulvinaria sp.',
    'Punta Morada de la papa (Fitoplasma)',
    'Puto californicus',
    'Putu sp.',
    'Pycnomerus sp.',
    'Pyllachora sp.',
    'Pyrenophora teres',
    'Pyricularia koleroga',
    'Pyricularia oryzae',
    'Pyricularia sp.',
    'Pythium sp.',
    'Radopholus similis',
    'Radopholus sp.',
    'Ralstonia solanacearum',
    'Ralstonia solanacearum raza 2',
    'Ramosulus corrugipennis',
    'Raoultella terrigena',
    'Raphanus raphanistrum',
    'Rhabditis sp.',
    'Rhaphigaster sp.',
    'Rhinostomus barbirostris',
    'Rhizobium sp.',
    'Rhizoctonia solani',
    'Rhizoctonia sp.',
    'Rhizoglyphus sp.',
    'Rhizopus sp.',
    'Rhopalosiphum maidis',
    'Rhopalosiphum padi',
    'Rhynchophorus ferrugineus',
    'Rhynchophorus palmarum',
    'Rhynchospora sp.',
    'Rhytismatales sp.',
    'Rhyzopertha dominica',
    'Rorippa mexicana',
    'Rorippa nasturtium- aquaticum',
    'Rosellinia necatrix',
    'Rottboellia cochinchinensis',
    'Rottboellia exaltata',
    'Rotylenchus sp.',
    'Ruellia floribunda',
    'Rumex acetosella',
    'Rumex crispus',
    'Rumex obtusifolius',
    'Rumex sp.',
    'Rupela albinella',
    'Saccharicoccus sacchari',
    'Sagalassa valida',
    'Sahyadrassus malabaricus',
    'Saissetia coffeae',
    'Saissetia sp.',
    'Saldula saltatoria',
    'Salvia sp.',
    'Salvia tiliifolia',
    'Sarasinula plebeia',
    'Sarocladium sp.',
    'Scaeva sp.',
    'Scaptotrigona subobscuripennis',
    'Scatella stagnalis',
    'Schistocerca sp.',
    'Schizaphis graminum',
    'Sciara sp.',
    'Scirtothrips sp.',
    'Scleranthus annuus',
    'Scleria setuloso-ciliata',
    'Sclerotinia sp.',
    'Sclerotium sp.',
    'Scolytodes sp.',
    'Scolytus sp.',
    'Scoparia dulcis',
    'Scoparia sp.',
    'Scrobipalpula sp',
    'Scrophulariaceae',
    'Scutellonema sp.',
    'Scymnus sp.',
    'Selenaspidus articulatus',
    'Selenaspidus sp.',
    'Selenothrips rubrocinctus',
    'Senecio sp.',
    'Senecio vulgaris',
    'Septoria sp.',
    'Sesbania sp.',
    'Setaria sp.',
    'Setariopsis sp.',
    'Sibine fusca',
    'Sibine sp.',
    'Sida acuta',
    'Sida rhombifolia',
    'Sida spinosa',
    'Sidastrum paniculatum',
    'Sidastrum sp.',
    'Silene gallica',
    'Silvanus planatus',
    'Sipha flava',
    'Sisymbrium irio',
    'Sitophilus granarius',
    'Sitophilus oryzae',
    'Sitophilus sp.',
    'Sitophilus zeamais',
    'Sogatodes oryzicola',
    'Solanaceae',
    'Solanum americanum',
    'Solanum erianthum',
    'Solanum nigrescens',
    'Solanum nigrum',
    'Solanum pubigerum',
    'Solanum sp.',
    'Solanun americanum',
    'Solenopsis sp.',
    'Solitaria Sanguinalis',
    'Sonchus oleraceus',
    'Sonchus sp.',
    'Sorghum arundinaceum',
    'Sparganothis pilleriana',
    'Spergula arvensis',
    'Spermacoce exilis',
    'Spermacoce sp.',
    'Spermacose alata',
    'Sphaceloma sp.',
    'Sphaerotheca fuliginea',
    'Sphagneticola trilobata',
    'Spiroplasmas',
    'Spodoptera frugiperda',
    'Spodoptera sp.',
    'Spongospora sp.',
    'Spongospora subterranea',
    'Stachytarpheta jamaicensis',
    'Stategus aloeus',
    'Steirastoma breve',
    'Stellaria media',
    'Stemphylium sp.',
    'Steneotarsonemus sp.',
    'Steneotarsonemus spinki',
    'Stenoma catenifer',
    'Stenoma sp.',
    'Stenostephanus sp.',
    'Stictopelta sp.',
    'Strategus aloeus',
    'Strawberry Latent Ringspot Virus (SLRSV)',
    'Stromatium barbatum',
    'Stromatium unicolor',
    'Succinea sp.',
    'Sunblotch',
    'Symmetrischema tangolias',
    'Synchlora sp.',
    'Synchytrium endobioticum',
    'Synedrella nodiflora',
    'Syngamia sp.',
    'Syrphus ribessi',
    'Tagosodes orizicolus',
    'Talinum paniculatum',
    'Tamarillo mosaic virus',
    'Tanacetum vulgare',
    'Taphrina deformans',
    'Taphrina sp.',
    'Taraxacum officinale',
    'Tecaphora solani',
    'Tecia solanivora',
    'Telotylenchus sp.',
    'Tenebrio maritimus',
    'Tenebrio molitor',
    'Termites sp.',
    'Termitidae',
    'Tetranychus cinnabarinnus',
    'Tetranychus sp.',
    'Tetranychus urticae',
    'Tetylenchus sp.',
    'Thecaphora solani',
    'Thereva sp.',
    'Thielaviopsis basicola',
    'Thielaviopsis sp.',
    'Thrips florum',
    'Thrips palmi',
    'Thrips sp.',
    'Thrips tabaci',
    'Thunbergia alata',
    'Thunbergia sp.',
    'Thylenchus sp.',
    'Thyrinteina arnobia',
    'Tibouchina longifolia',
    'Tibraca limbativentris',
    'Tinantia erecta',
    'Tipula sp.',
    'Tobacco Mosaic virus',
    'Tobacco rattle virus',
    'Tortigonalia longicaudata',
    'Torula sp.',
    'Toxoptera aurantii',
    'Toxoptera citri',
    'Toxoptera citricida',
    'Toxoptera sp.',
    'Tradescantia zanonia',
    'Tranzschelia sp.',
    'Treehopper sp.',
    'Trialeurodes sp',
    'Trialeurodes vaporariorum',
    'Tribolium castaneum',
    'Tribolium confusum',
    'Trichoderma sp.',
    'Trichodorus sp.',
    'Trichogramma sp.',
    'Trichoplusia sp.',
    'Trichothecium sp.',
    'Tridax procumbens',
    'Trifolium repens',
    'Trigonogenius globulus',
    'Trigonogenius sp.',
    'Trimerotropis pallidipennis',
    'Trioza erytreae',
    'Trioza sp.',
    'Tripogandra amplexans',
    'Trisetum spicatum',
    'Trogoderma granarium',
    'Trogoderma sp.',
    'Tropaeolum sp.',
    'Tuta absoluta',
    'Tylenchorhynchus sp.',
    'Tylenchus sp.',
    'Typhaea sp.',
    'Unaspis citri',
    'Unaspis sp.',
    'Uromyces sp.',
    'Urophorus sp.',
    'Urtica urens',
    'Ustilaginoidea sp.',
    'Ustilaginoidea virens',
    'Ustilago maydis',
    'Ustilago sp.',
    'Ustilago zeae',
    'Venturia sp.',
    'Verbena gracilis',
    'Verbena litoralis',
    'Verbena menthifolia',
    'Verbena sp.',
    'Vernonia cinerea',
    'Veronica peregrina',
    'Veronica persica',
    'Verticilium sp.',
    'Verticillium sp.',
    'Vigna lasiocarpa',
    'Viguiera sp.',
    'Vinsonia sp.',
    'Virgibacillus pantothenticus',
    'Virus de la hoja blanca (VHB)',
    'Virus de la necrosis del arroz (RSNV)',
    'Virus del enrollamiento de la vid (GLRaV)',
    'Virus del jaspeado del tabaco (TEV)',
    'Virus del mosaico de las brácteas del banano (BBrMV)',
    'Virus del Mosaico del maiz (MMV)',
    'Virus del Rayado Fino del Maíz (MRFV)',
    'Wasmannia auropunctata',
    'Wasmannia sp.',
    'Watermelon mosaic virus (WMV)',
    'Xanthium spinosum',
    'Xanthomona citri pv manguiferae',
    'Xanthomonas sp.',
    'Xiphinema sp.',
    'Xyleborus affinis',
    'Xyleborus ferrugineus',
    'Xyleborus sp.',
    'Xyleborus spinulosus',
    'Xylella fastidiosa',
    'Xylopsocus capucinus',
    'Xylosandrus compactus',
    'Xylosandrus morigerus',
    'Xylosma sp.',
    'Xyteutes ceramicus',
    'Zelus renardii',
    'Zelus sp.',
    'Zygotylenchus sp.'
  ];

  final _tipoPlaga = [
    'BACTERIA',
    'INSECTO',
    'VIRUS',
    'HONGO',
    'NEMÁTODO',
    'MALEZA',
    'ÁCAROS',
    'MOLUSCOS',
    'FITOPLASMA',
  ];

  final _fasePlaga = [
    'NO APLICA',
    'DESARROLLO VEGETATIVO',
    'PLANTA',
    'HUEVO',
    'LARVA/NINFA',
    'PUPA',
    'IMAGO/ADULTO',
  ];

  final _organoAfectado = [
    'NO APLICA',
    'BROTE',
    'GRANO',
    'BULBO/TUBÉRCULO/RIZOMA',
    'FOLIOLOS',
    'HOJA',
    'FLOR',
    'FRUTO/GRANO/SEMILLA/VAINA',
    'INFLORESCENCIA',
    'RAÍZ',
    'RAMA/RAMILLA',
    'TALLO/TRONCO',
    'TODA LA PLANTA',
  ];

  final _distribucionPlaga = [
    'NO APLICA',
    'DISTRIBUCIÓN GENERALIZADA',
    'BROTE',
  ];

  final _tipoMuestra = [
    'Raíz',
    'Ramas',
    'Tubérculos',
    'Bulbos',
    'Flores',
    'Cormos',
    'Frutas',
    'Tallos',
    'Granos',
    'Hojas',
    'Brotes',
    'Semilla',
    'Planta',
    'Suelo',
    'Trampa insectos en alcohol',
  ];

  final _conservacionMuestra = [
    'Natural',
    'Refrigerada',
    'Envase apropiado',
    'Etiquetado',
  ];

  List<String> getEspecieVegetalString() {
    return _especie;
  }

  List<String> getDiagnosticoVisual() {
    return _diagnosticoVisual;
  }

  List<String> getTipoPlagaString() {
    return _tipoPlaga;
  }

  List<DropdownMenuItem<String>> getUnidad() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _unidad) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getSitioOperacion() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _sitioOperacion) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getCondicionProduccion() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _condicionProduccion) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getEtapaCultivo() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _etapaCultivo) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getActividad() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _actividad) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getManejoSitio() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _manejoSitio) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getTipoPlaga() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _tipoPlaga) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getFasePlaga() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _fasePlaga) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getOrganoAfectado() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _organoAfectado) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getDistribucionPlaga() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _distribucionPlaga) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getTipoMuestra() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _tipoMuestra) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getConservacionMuestra() {
    List<DropdownMenuItem<String>> items = [];
    for (String item in _conservacionMuestra) {
      items.add(DropdownMenuItem(value: item, child: Text(item)));
    }
    return items;
  }
}
